name: Node.js CI

# Se ejecuta al hacer push o pull request a la rama main
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: "ğŸ”½ Clonar el cÃ³digo"
        uses: actions/checkout@v3

      - name: "âš™ï¸ Configurar Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: "ğŸ“¦ Instalar dependencias"
        run: npm install

      - name: "ğŸ§ª Ejecutar pruebas"
        run: npm test
